# Generated by Django 2.1.1 on 2018-09-07 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('statistic_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(max_length=2000)),
                ('week', models.IntegerField(max_length=100)),
                ('month', models.IntegerField(max_length=20)),
                ('elect_eur', models.FloatField()),
                ('elect_kwh', models.FloatField()),
                ('heating_eur', models.FloatField()),
                ('heating_kwh', models.FloatField()),
                ('water_eur', models.FloatField()),
                ('water_litres', models.FloatField()),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.School')),
            ],
            options={
                'db_table': 'statistics',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('photoName', models.CharField(max_length=100)),
                ('createdDate', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
